development:
  adapter: postgresql
  encoding: unicode
  database: sortable-tables-development
  pool: 5
  username: tomek
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sortable-tables-test
  pool: 5
  username: tomek
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sortable-tables-production
  pool: 5
  username: tomek
  password: